name: 'Repochat Action'
description: 'Chat with your repo in one Action'
author: 'flavienbwk'
inputs:
  dirs_to_scan:
    description: 'Comma-separated list of directories that you want to chat about'
    required: true
  interface_password:
    description: 'Password to access the interface'
    required: false
    default: ''
  openai_api_key:
    description: 'Your OpenAI API key'
    required: true
  openai_model_type_inference:
    description: 'OpenAI model type for inference'
    default: 'gpt-4o-mini'
    required: false
  openai_model_type_embedding:
    description: 'OpenAI model type for embedding'
    default: 'text-embedding-3-small'
    required: false
  provider_name:
    description: 'Cloud provider'
    default: 'scaleway'
    required: false
  provider_key_id:
    description: 'Cloud provider API key ID'
    required: true
  provider_key_secret:
    description: 'Cloud provider API key secret'
    required: true
  provider_default_region:
    description: 'Cloud provider default region'
    required: true
  provider_default_zone:
    description: 'Cloud provider default zone'
    required: true
  provider_project_id:
    description: 'Cloud provider project ID (Scaleway specific)'
    required: false
  pg_connection_string:
    description: 'PostgreSQL connection string'
    required: false
    default: ''
  cpu_limit:
    description: 'CPU limit for the container'
    required: false
    default: '1000'
  memory_limit:
    description: 'Memory limit for the container'
    required: false
    default: '1024'
  min_scale:
    description: 'Minimum scale for the container'
    required: false
    default: '1'
  max_scale:
    description: 'Maximum scale for the container'
    required: false
    default: '1'
runs:
  using: 'node16'
  main: 'lib/index.js'
branding:
  icon: 'code'
  color: 'purple'
