services:

  repochat:
    build: .
    environment:
      MODE: api
      REPO_NAME: ${REPO_NAME}
      REPO_URL: ${REPO_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      INGEST_SECRET: ${INGEST_SECRET}
      MODEL_TYPE_INFERENCE: ${MODEL_TYPE_INFERENCE}
      MODEL_TYPE_EMBEDDING: ${MODEL_TYPE_EMBEDDING}
      CLEAR_DB_AT_RESTART: ${CLEAR_DB_AT_RESTART}
      INTERFACE_PASSWORD: ${INTERFACE_PASSWORD}
    ports:
      - "3001:80"
