services:

  repochat:
    build: .
    environment:
      REPO_NAME: ${REPO_NAME}
      REPO_URL: ${REPO_URL}
      REPO_PATH: ${REPO_PATH}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      INGEST_SECRET: ${INGEST_SECRET}
      MODEL_TYPE_INFERENCE: ${MODEL_TYPE_INFERENCE}
      MODEL_TYPE_EMBEDDING: ${MODEL_TYPE_EMBEDDING}
      CLEAR_DB_AT_RESTART: ${CLEAR_DB_AT_RESTART}
      MODE: directory
    volumes:
      - ./api/example:/usr/app/api/example:ro  # for directory mode only
      # - chromadb:/usr/app/db/chroma:rw  # to persist DB across reboots if desired (uncomment volumes)
    ports:
      - "3001:80"

# volumes:
#   chromadb:
